name: Llista de la compra
description: Llista de la compra amb checklist, importació ràpida i categorització local
version: "1.0.0"
slug: shopping-list
init: false
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
ports:
  8000/tcp: 8000
map:
  - type: volume
    name: shopping_list_data
    read_only: false
options:
  port: 8000
schema:
  port: int
